paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Los Productos fueron obtenidos OK desde la DB
        "500":
          description: Error interno del servidor
    post:
      summary: Graba un producto
      tags:
        - Productos
      responses:
        "201":
          description: Producto creado
        "500":
          description: Error interno del servidor