paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Los Productos fueron obtenidos OK desde la Base de Datos          
        "500":
          description: Error interno del servidor

  /api/products/{id}:
    get:
      summary: Obtiene un producto de la base de datos por id
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: id del producto que se está solicitando
        schema:
          type: string
      # - name: Authorization
      #   in: header
      #   required: true
      #   description: Token de autenticación
      #   schema:
      #     type: string            
      responses:
        "200":
          description: Recupera un producto de la DB, según el id que enviamos en la ruta como parámetro
        "500":
          description: Error interno del servidor




    post:
      summary: Graba un producto
      tags:
        - Productos
      responses:
        "201":
          description: Producto creado
        "500":
          description: Error interno del servidor
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado de mongo
        first_name:
          type: string
          description: Nombre del usuario
        last_name:
          type: string
          description: Apellido...    
        email:
          type: string
          description: Correo electronico
        password: 
          type: string
          description: contraseña de acceso  
      example:
        _id: ObjectId("60acc54545c8e82e0475f73a")
        first_name: Diego
        last_name: Polverelli
        email: diegopolverelli@hotmail.com
        password: 123